//carts
export const FETCH_CARTS_REQUEST = "FETCH_CARTS_REQUEST";
export const FETCH_CARTS_SUCCESS = "FETCH_CARTS_SUCCESS";
export const FETCH_CARTS_FAILURE = "FETCH_CARTS_FAILURE";
export const ADD_TO_CART = "ADD_TOO_CART"